## Phase 1 — Data inspection

We will load the CSV and inspect its size, columns, sample rows, data types, statistics, missing values, duplicates, and distinct values in key categorical columns. This gives us a baseline before cleaning.

**Cell 1 — Load the data**

```python
import pandas as pd
from IPython.display import display

df = pd.read_csv("sales_5000.csv")
```

**Cell 2 — Dataset size, columns, and sample rows**

```python
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")
print("Column names:", df.columns.tolist())

display(df.head(10))
```

**Cell 3 — Data types and DataFrame information**

```python
display(df.dtypes.to_frame(name="data_type"))
df.info()
```

**Cell 4 — Statistical information**

```python
display(df.describe(include="all").T)
```

**Cell 5 — Missing values**

```python
missing_summary = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": (df.isna().mean() * 100).round(2)
})

display(missing_summary.sort_values("missing_count", ascending=False))
```

**Cell 6 — Duplicate rows**

```python
print("Exact duplicate rows:", df.duplicated().sum())

display(df.loc[df.duplicated(keep=False)].head(20))
```

**Cell 7 — Unique values and counts for categorical columns**

```python
for column in ["region", "payment_method", "status"]:
    if column in df.columns:
        print(f"\n{column}:")
        display(df[column].value_counts(dropna=False).rename("count").to_frame())
```

**Cell 8 — Unique values in each column**

```python
for column in df.columns:
    print(f"{column}: {df[column].nunique(dropna=False)} unique values")
```

In [1]:
import pandas as pd

df = pd.read_csv('data/sales_data.csv')
df.head()

,order_id,order_date,product,qty,price,region,customer_id,payment_method,status
0,2320,2025-09-28,Juice,unknown,1450,North,CUST0465,Cash,Pending
1,1964,2025-05-13,Juice,3,1650,South,CUST0518,Transfer,Completed
2,1080,2025-09-17,Milk,5,1100,South,CUST0502,Transfer,Returned
3,3743,2025-06-02,Tomato Paste,7pcs,640,East,NaN,POS,Completed
4,2792,2025-07-08,Milk,4,1420,West,CUST0458,Cash,Completed

In [2]:
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")

print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 10 rows:")
display(df.head(10))

print("\nLast 5 rows:")
display(df.tail())

Rows: 5,200
Columns: 9

Column names:
['order_id', 'order_date', 'product', 'qty', 'price', 'region', 'customer_id', 'payment_method', 'status']

First 10 rows:

,order_id,order_date,product,qty,price,region,customer_id,payment_method,status
0,2320,2025-09-28,Juice,unknown,1450,North,CUST0465,Cash,Pending
1,1964,2025-05-13,Juice,3,1650,South,CUST0518,Transfer,Completed
2,1080,2025-09-17,Milk,5,1100,South,CUST0502,Transfer,Returned
3,3743,2025-06-02,Tomato Paste,7pcs,640,East,NaN,POS,Completed
4,2792,2025-07-08,Milk,4,1420,West,CUST0458,Cash,Completed
5,3708,2025-07-07,Rice,4,2010,West,CUST0317,Cash,Completed
6,2982,2025-12-28,Bread,4,1010,South,CUST0002,POS,Completed
7,3656,2025-01-07,Detergent,NaN,1740,West,CUST0058,POS,Completed
8,1462,2025-04-08,Toilet Roll,1,790,West,CUST0232,Cash,Completed
9,4537,2025-03-02,Water,7,470,South,CUST0264,Transfer,Completed

Last 5 rows:

,order_id,order_date,product,qty,price,region,customer_id,payment_method,status
5195,5113,2025-05-07,Detergent,NaN,1750,North,CUST0262,POS,Pending
5196,5748,2025-04-28,Eggs,5,2420,North,CUST0445,Cash,Pending
5197,5626,2025-10-18,Coffee,6,1910,South,CUST0090,POS,Pending
5198,1418,2025-05-31,Beans,1,NaN,East,CUST0076,Transfer,NaN
5199,4585,2025-06-10,Coffee,4,2140,South,CUST0453,POS,Pending

In [3]:
print("Data types:")
display(df.dtypes.to_frame(name="data_type"))

print("\nDataFrame information:")
df.info()

Data types:

               data_type
order_id             str
order_date           str
product              str
qty                  str
price                str
region               str
customer_id          str
payment_method       str
status               str

DataFrame information:
<class 'pandas.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        5200 non-null   str
 1   order_date      5107 non-null   str
 2   product         5070 non-null   str
 3   qty             5015 non-null   str
 4   price           5084 non-null   str
 5   region          5055 non-null   str
 6   customer_id     5034 non-null   str
 7   payment_method  5097 non-null   str
 8   status          5122 non-null   str
dtypes: str(9)
memory usage: 365.8 KB

In [4]:
print("Descriptive statistics for numeric columns:")
display(df.describe())

print("\nDescriptive statistics for all columns:")
display(df.describe(include="all").T)

Descriptive statistics for numeric columns:

,order_id,order_date,product,qty,price,region,customer_id,payment_method,status
count,5200,5107,5070,5015,5084,5055,5034,5097,5122
unique,5150,564,78,22,248,21,673,9,8
top,1084,2025-08-21,Toothpaste,3,760,South,CUST0387,Transfer,Completed
freq,2,29,250,729,57,1266,18,2259,3868

Descriptive statistics for all columns:

               count unique         top  freq
order_id        5200   5150        1084     2
order_date      5107    564  2025-08-21    29
product         5070     78  Toothpaste   250
qty             5015     22           3   729
price           5084    248         760    57
region          5055     21       South  1266
customer_id     5034    673    CUST0387    18
payment_method  5097      9    Transfer  2259
status          5122      8   Completed  3868

In [5]:
missing_summary = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": (df.isna().mean() * 100).round(2),
    "non_missing_count": df.notna().sum()
})

display(missing_summary.sort_values("missing_count", ascending=False))

                missing_count  missing_percent  non_missing_count
qty                       185             3.56               5015
customer_id               166             3.19               5034
region                    145             2.79               5055
product                   130             2.50               5070
price                     116             2.23               5084
payment_method            103             1.98               5097
order_date                 93             1.79               5107
status                     78             1.50               5122
order_id                    0             0.00               5200

In [6]:
exact_duplicate_count = df.duplicated().sum()

print(f"Exact duplicate rows: {exact_duplicate_count:,}")

print("\nExample exact duplicate rows:")
display(df.loc[df.duplicated(keep=False)].sort_values(list(df.columns)).head(20))

if "order_id" in df.columns:
    repeated_order_ids = df["order_id"].duplicated(keep=False)
    print(f"\nRows with an order_id that appears more than once: {repeated_order_ids.sum():,}")
    display(df.loc[repeated_order_ids].sort_values("order_id").head(20))

Exact duplicate rows: 21

Example exact duplicate rows:

,order_id,order_date,product,qty,price,region,customer_id,payment_method,status
63,1084,2025-09-11,Rice,8,1720,West,CUST0364,POS,Completed
1869,1084,2025-09-11,Rice,8,1720,West,CUST0364,POS,Completed
2067,1149,2025-09-24,Maggi,3,530,East,CUST0063,POS,Pending
4908,1149,2025-09-24,Maggi,3,530,East,CUST0063,POS,Pending
4318,1289,2025-05-14,Yam,3,1800,South,CUST0101,POS,Completed
4824,1289,2025-05-14,Yam,3,1800,South,CUST0101,POS,Completed
2988,1315,2025-05-09,Carrot,10,920,South,CUST0609,Cash,Completed
4278,1315,2025-05-09,Carrot,10,920,South,CUST0609,Cash,Completed
1293,1856,2025-07-15,Sugar,5,1310,North,CUST0637,Cash,Completed
5110,1856,2025-07-15,Sugar,5,1310,North,CUST0637,Cash,Completed
1214,2350,2025-06-04,Tea,3,1060,South,CUST0559,Transfer,Pending
5065,2350,2025-06-04,Tea,3,1060,South,CUST0559,Transfer,Pending
3754,2508,2025-04-26,Tomato Paste,8,620,West,CUST0182,POS,Completed
4912,2508,2025-04-26,Tomato Paste,8,620,West,CUST0182,POS,Completed
3564,2735,2025-08-16,Groundnut Oil,10,2420,North,CUST0334,Cash,Completed
3566,2735,2025-08-16,Groundnut Oil,10,2420,North,CUST0334,Cash,Completed
362,2810,2025-08-26,Carrot,1,900,North,CUST0223,Cash,Completed
2063,2810,2025-08-26,Carrot,1,900,North,CUST0223,Cash,Completed
683,3129,2025-07-11,Pepper,3,650,South,CUST0472,Cash,Completed
4377,3129,2025-07-11,Pepper,3,650,South,CUST0472,Cash,Completed

Rows with an order_id that appears more than once: 100

,order_id,order_date,product,qty,price,region,customer_id,payment_method,status
63,1084,2025-09-11,Rice,8,1720,West,CUST0364,POS,Completed
1869,1084,2025-09-11,Rice,8,1720,West,CUST0364,POS,Completed
4908,1149,2025-09-24,Maggi,3,530,East,CUST0063,POS,Pending
2067,1149,2025-09-24,Maggi,3,530,East,CUST0063,POS,Pending
3863,1286,2025-02-07,Beans,2,1590,NaN,CUST0491,Transfer,Pending
1339,1286,2025-02-07,Beans,2,1590,West,CUST0491,NaN,Pending
4824,1289,2025-05-14,Yam,3,1800,South,CUST0101,POS,Completed
4318,1289,2025-05-14,Yam,3,1800,South,CUST0101,POS,Completed
4278,1315,2025-05-09,Carrot,10,920,South,CUST0609,Cash,Completed
2988,1315,2025-05-09,Carrot,10,920,South,CUST0609,Cash,Completed
309,1333,2025-07-07,NaN,3,1360,North,CUST0502,Cash,Completed
214,1333,2025-07-07,Sugar,3,1360,North,CUST0502,Cash,Completed
2887,1530,21/02/2025,Coffee,3,1750,West,CUST0326,Cash,Completed
4429,1530,2025-02-21,Coffee,3,1750,West,CUST0326,Cash,Completed
1302,1797,2025-12-27,Groundnut Oil,5,2690,East,CUST0395,POS,Completed
1595,1797,2025-12-27,Groundnut Oil,5,2690,East,CUSTOMER-0395,POS,Completed
1293,1856,2025-07-15,Sugar,5,1310,North,CUST0637,Cash,Completed
5110,1856,2025-07-15,Sugar,5,1310,North,CUST0637,Cash,Completed
4608,1897,2025-04-12,Yam,1,1570,South,CUST0387,POS,Pending
3407,1897,2025-04-12,Yam,7pcs,1570,South,CUST0387,POS,RETURNED

In [7]:
category_columns = ["region", "payment_method", "status"]

for column in category_columns:
    if column in df.columns:
        print(f"\n{column}: {df[column].nunique(dropna=False)} distinct values, including missing values")
        display(
            df[column]
            .value_counts(dropna=False)
            .rename_axis(column)
            .reset_index(name="count")
        )

region: 22 distinct values, including missing values

     region  count
0     South   1266
1      West   1239
2     North   1220
3      East   1207
4       NaN    145
5      WEST     13
6     west      11
7      east     11
8     NORTH     10
9     south     10
10    West       9
11     Noth      9
12     west      7
13   North       7
14   South       7
15    East       5
16   Northh      5
17     EAST      5
18    SOUTH      4
19     Sout      4
20    north      3
21  EASTERN      3

payment_method: 10 distinct values, including missing values

  payment_method  count
0       Transfer   2259
1           Cash   1490
2            POS   1255
3            NaN    103
4  Bank Transfer     20
5           POS      17
6            Pos     17
7           cash     16
8           card     12
9       transfer     11

status: 9 distinct values, including missing values

      status  count
0  Completed   3868
1    Pending    786
2   Returned    390
3        NaN     78
4  completed     19
5   pending      17
6     return     16
7   Complete     14
8   RETURNED     12

In [8]:
print(df.duplicated().sum())

21

In [9]:
if "order_id" in df.columns:
    repeated_order_ids = df["order_id"].duplicated(keep=False)
    print(f"\nRows with an order_id that appears more than once: {repeated_order_ids.sum():,}")
    order_dup = df.loc[repeated_order_ids].sort_values("order_id")

order_dup

Rows with an order_id that appears more than once: 100

,order_id,order_date,product,qty,price,region,customer_id,payment_method,status
63,1084,2025-09-11,Rice,8,1720,West,CUST0364,POS,Completed
1869,1084,2025-09-11,Rice,8,1720,West,CUST0364,POS,Completed
4908,1149,2025-09-24,Maggi,3,530,East,CUST0063,POS,Pending
2067,1149,2025-09-24,Maggi,3,530,East,CUST0063,POS,Pending
3863,1286,2025-02-07,Beans,2,1590,NaN,CUST0491,Transfer,Pending
...,...,...,...,...,...,...,...,...,...
3821,5848,2025-09-30,Water,4,520,East,NaN,Cash,Completed
3674,5977,2025-11-08,Juice,9,1610,West,CUST0525,Cash,Completed
3723,5977,2025-11-08,Juice,9,1610,West,CUST0525,Cash,Completed
4109,6019,2025-04-06,Bread,4,1070,North,CUST0372,Cash,Completed
1384,6019,2025-04-06,Bread,4,1070,North,CUST0372,Cash,Completed

In [10]:
numeric_columns_to_check = ["qty", "price"]

for column in numeric_columns_to_check:
    if column in df.columns:
        numeric_test = pd.to_numeric(df[column], errors="coerce")
        nonblank = df[column].notna() & df[column].astype("string").str.strip().ne("")
        suspicious_mask = nonblank & numeric_test.isna()

        print(f"\n{column}:")
        print(f"Nonblank values that do not convert directly to numbers: {suspicious_mask.sum():,}")
        display(df.loc[suspicious_mask, [column]].drop_duplicates().sort_values(column))

qty:
Nonblank values that do not convert directly to numbers: 56

         qty
210  3 units
3       7pcs
116     five
109      two
0    unknown

price:
Nonblank values that do not convert directly to numbers: 57

             price
528          1,500
151             2k
467  not available
434        unknown
219          ₦1200

# Phase 2 — Data cleaning and preparation


We will clean a working copy of the data, keeping raw_df unchanged. The steps are to trim whitespace, standardize common missing-value markers, normalize category labels, inspect malformed numeric values, convert quantity and price, remove exact duplicate rows, and fill missing numeric values using the median for the same product where possible.


Filling by product assumes that values for the same product are more comparable than values across different products. Missing values that cannot be filled from a product group will remain missing rather than being assigned an unsupported value. Repeated order_id values will not be removed automatically.

In [11]:
# Trim whitespace from text columns.
text_columns = df.select_dtypes(include=["object", "string"]).columns

for column in text_columns:
    df[column] = df[column].astype("string").str.strip()

print("Whitespace trimmed from text columns.")

Whitespace trimmed from text columns.

In [12]:
# Drop duplicate rows, keeping the first occurrence.
initial_row_count = df.shape[0]
df = df.drop_duplicates(keep="first")
final_row_count = df.shape[0]
print(f"Dropped {initial_row_count - final_row_count:,} duplicate rows. Remaining rows: {final_row_count:,}.")

Dropped 21 duplicate rows. Remaining rows: 5,179.

In [13]:
for column in df.columns:
    df[column] = df[column].astype("string").str.strip().replace({"": pd.NA, "NA": pd.NA, "N/A": pd.NA, "null": pd.NA, "NULL": pd.NA})
    df[column] = df[column].str.title()

In [14]:
df['customer_id'] = df['customer_id'].str.upper()

In [15]:
# df["estimated_qty"] = df["qty"]
# missing_qty = df["estimated_qty"].isna()

In [16]:
df.head()

,order_id,order_date,product,qty,price,region,customer_id,payment_method,status
0,2320,2025-09-28,Juice,Unknown,1450,North,CUST0465,Cash,Pending
1,1964,2025-05-13,Juice,3,1650,South,CUST0518,Transfer,Completed
2,1080,2025-09-17,Milk,5,1100,South,CUST0502,Transfer,Returned
3,3743,2025-06-02,Tomato Paste,7Pcs,640,East,<NA>,Pos,Completed
4,2792,2025-07-08,Milk,4,1420,West,CUST0458,Cash,Completed

In [17]:
import pandas as pd

df["qty_original"] = df["qty"]

qty_text = (
    df["qty"]
    .astype("string")
    .str.strip()
    .str.casefold()
    .str.replace(r"\s*(?:pcs?|units?)\s*$", "", regex=True)
)

# Handle number words present in the data.
qty_text = qty_text.replace({"two": "2", "five": "5"})

qty_numeric = pd.to_numeric(qty_text, errors="coerce")

# Round fractional quantities to whole numbers, then convert to nullable integers.
df["qty"] = qty_numeric.round().astype("Int64")

In [18]:
print(df.price.isna().sum())

116

In [19]:
df["price_original"] = df["price"]

price_text = (
    df["price"]
    .astype("string")
    .str.strip()
    .str.casefold()
    .str.replace(r"^[n₦]\s*", "", regex=True)
    .str.replace(",", "", regex=False)
    .str.replace(r"\s+", "", regex=True)
)

# Identify and remove a trailing "k", then multiply those values by 1,000.
in_thousands = price_text.str.endswith("k", na=False)
price_text = price_text.str.replace(r"k$", "", regex=True)

price_numeric = pd.to_numeric(price_text, errors="coerce")
price_numeric.loc[in_thousands] *= 1000

df["price"] = price_numeric.round().astype("Int64")

In [20]:
df.head(20)

,order_id,order_date,product,qty,price,region,customer_id,payment_method,status,qty_original,price_original
0,2320,2025-09-28,Juice,<NA>,1450,North,CUST0465,Cash,Pending,Unknown,1450
1,1964,2025-05-13,Juice,3,1650,South,CUST0518,Transfer,Completed,3,1650
2,1080,2025-09-17,Milk,5,1100,South,CUST0502,Transfer,Returned,5,1100
3,3743,2025-06-02,Tomato Paste,7,640,East,<NA>,Pos,Completed,7Pcs,640
4,2792,2025-07-08,Milk,4,1420,West,CUST0458,Cash,Completed,4,1420
5,3708,2025-07-07,Rice,4,2010,West,CUST0317,Cash,Completed,4,2010
6,2982,2025-12-28,Bread,4,1010,South,CUST0002,Pos,Completed,4,1010
7,3656,2025-01-07,Detergent,<NA>,1740,West,CUST0058,Pos,Completed,<NA>,1740
8,1462,2025-04-08,Toilet Roll,1,790,West,CUST0232,Cash,Completed,1,790
9,4537,2025-03-02,Water,7,470,South,CUST0264,Transfer,Completed,7,470
10,5694,2025-09-12,Milk,9,1250,South,CUST0610,Pos,Completed,9,1250
11,Ord-5412,2025-07-06,Beans,4,1650,South,CUST0439,Pos,Completed,4,1650
12,1412,2025-06-07,Cabbage,6,750,West,CUST0002,Pos,Returned,6,750
13,1273,2025-07-12,Cabbage,1,900,West,CUST0357,Transfer,Returned,1,900
14,3737,2025-04-04,Rice,7,1910,North,CUST0361,Cash,Returned,7,1910
15,2501,2025-09-22,Carrot,1,910,South,CUST0063,Transfer,Pending,1,910
16,3630,2025-07-02,Sugar,3,1520,East,CUST0389,Transfer,Completed,3,1520
17,3327,2025-04-19,Sugar,7,1290,South,CUST0182,Cash,Pending,7,1290
18,5121,2025-08-20,Toilet Roll,1,920,East,CUST0215,Transfer,Completed,1,920
19,1907,2025-12-10,Cabbage,3,900,East,CUST0595,Transfer,<NA>,3,900

In [21]:
import pandas as pd

df["order_date_original"] = df["order_date"]

date_formats = [
    "%Y-%m-%d",       # 2025-05-20
    "%Y/%m/%d",       # 2025/05/20
    "%Y|%m|%d",       # 2025|05|20
    "%b %d, %Y",      # Apr 22, 2025 or Oct 22, 2025
    "%B %d, %Y",      # April 22, 2025 or October 22, 2025
    "%d %b %Y",       # 22 Oct 2025
    "%d %B %Y",       # 22 October 2025
    "%d/%m/%Y",       # 26/07/2025; day-first, as indicated by the data
    "%m/%d/%Y",       # Used only if day-first parsing fails
    "%m-%d-%Y",       # 07-23-2025
    "%d-%m-%Y",
]

def parse_order_date(value):
    if pd.isna(value):
        return pd.NaT

    text = str(value).strip()

    if not text or text.casefold() in {
        "na", "n/a", "not recorded", "invalid", "unknown"
    }:
        return pd.NaT

    for date_format in date_formats:
        parsed = pd.to_datetime(text, format=date_format, errors="coerce")
        if not pd.isna(parsed):
            return parsed

    return pd.NaT

df["order_date"] = pd.to_datetime(df["order_date"].map(parse_order_date))

In [22]:
parse_failed = (
    df["order_date_original"].notna()
    & df["order_date"].isna()
)

print("Missing or unparsed dates:", df["order_date"].isna().sum())
print("\nOriginal values that could not be parsed:")
display(df.loc[parse_failed, ["order_date_original"]].drop_duplicates())

print("\nConverted date type:")
print(df["order_date"].dtype)

Missing or unparsed dates: 117

Original values that could not be parsed:

     order_date_original
499         Not Recorded
764           2025-00-12
816              Invalid
1003          31/02/2025
2303          2025-13-05
2839        Feb 30, 2025
3027          99-99-2025
3400          2025/99/01

Converted date type:
datetime64[us]

In [23]:
# Normalize payment method labels.
payment = df["payment_method"].astype("string").str.strip()
df.loc[payment.str.casefold().eq("bank transfer"), "payment_method"] = "Transfer"

# Normalize status labels.
status = df["status"].astype("string").str.strip()
df.loc[status.str.casefold().eq("complete"), "status"] = "Completed"
df.loc[status.str.casefold().eq("return"), "status"] = "Returned"

In [24]:
df.payment_method.value_counts(dropna=False)

payment_method
Transfer    2285
Cash        1498
Pos         1281
<NA>         103
Card          12
Name: count, dtype: Int64

In [25]:
df.status.value_counts(dropna=False)

status
Completed    3886
Pending       799
Returned      416
<NA>           78
Name: count, dtype: Int64

In [26]:
df.info()

<class 'pandas.DataFrame'>
Index: 5179 entries, 0 to 5199
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             5179 non-null   string
 1   order_date           5062 non-null   datetime64[us]
 2   product              5049 non-null   string
 3   qty                  4981 non-null   Int64
 4   price                5040 non-null   Int64
 5   region               5034 non-null   string
 6   customer_id          5013 non-null   string
 7   payment_method       5076 non-null   string
 8   status               5101 non-null   string
 9   qty_original         4994 non-null   string
 10  price_original       5063 non-null   string
 11  order_date_original  5086 non-null   string
dtypes: Int64(2), datetime64[us](1), string(9)
memory usage: 536.1 KB

In [27]:
if "order_id" in df.columns:
    repeated_order_ids = df["order_id"].duplicated(keep=False)
    print(f"\nRows with an order_id that appears more than once: {repeated_order_ids.sum():,}")
    order_dup = df.loc[repeated_order_ids].sort_values("order_id")

order_dup

Rows with an order_id that appears more than once: 58

,order_id,order_date,product,qty,price,region,customer_id,payment_method,status,qty_original,price_original,order_date_original
3863,1286,2025-02-07,Beans,2,1590,<NA>,CUST0491,Transfer,Pending,2,1590,2025-02-07
1339,1286,2025-02-07,Beans,2,1590,West,CUST0491,<NA>,Pending,2,1590,2025-02-07
214,1333,2025-07-07,Sugar,3,1360,North,CUST0502,Cash,Completed,3,1360,2025-07-07
309,1333,2025-07-07,<NA>,3,1360,North,CUST0502,Cash,Completed,3,1360,2025-07-07
2887,1530,2025-02-21,Coffee,3,1750,West,CUST0326,Cash,Completed,3,1750,21/02/2025
4429,1530,2025-02-21,Coffee,3,1750,West,CUST0326,Cash,Completed,3,1750,2025-02-21
1595,1797,2025-12-27,Groundnut Oil,5,2690,East,CUSTOMER-0395,Pos,Completed,5,2690,2025-12-27
1302,1797,2025-12-27,Groundnut Oil,5,2690,East,CUST0395,Pos,Completed,5,2690,2025-12-27
3407,1897,2025-04-12,Yam,7,1570,South,CUST0387,Pos,Returned,7Pcs,1570,2025-04-12
4608,1897,2025-04-12,Yam,1,1570,South,CUST0387,Pos,Pending,1,1570,2025-04-12
2907,2148,2025-10-12,Rice,4,1790,East,CUST0132,<NA>,Completed,4,1790,2025-10-12
952,2148,2025-10-12,Rice,4,1790,East,CUST0132,Cash,Completed,4,1790,12/10/2025
3776,2358,2025-03-11,Detergent,2,1870,West,CUST0309,Cash,Completed,2,1870,2025-03-11
4628,2358,2025-03-11,Detergent,2,1870,West,CUST0309,Cash,Completed,Two,1870,2025-03-11
3558,2783,2025-09-01,Water,7,470,North,CUST0200,Transfer,Returned,7,470,2025-09-01
1280,2783,2025-09-01,Water,7,470,North,CUST0200,Pos,Returned,7,470,2025-09-01
4866,2931,2025-03-29,Tea,9,1220,South,CUST0111,Transfer,Completed,9,1220,2025-03-29
2046,2931,2025-03-29,Tea,9,1220,South,UNKNOWN,Transfer,Completed,9,1220,2025-03-29
1479,3030,2025-11-03,Beans,1,1540,<NA>,CUST0387,Transfer,<NA>,1,1540,2025-11-03
173,3030,2025-11-03,Beans,1,1540,West,CUST0387,Transfer,Completed,1,1540,2025-11-03
4025,3136,2025-12-15,Detergent,3,1670,East,CUST0199,Transfer,Completed,3,1670,2025-12-15
4946,3136,2025-12-15,Detergent,3,1670,East,CUST0199,Transfer,Completed,3,1670,2025-12-15
2129,3239,2025-08-04,Soft Drink,6,770,South,CUST0393,Cash,Completed,6,770,2025-08-04
2599,3239,2025-08-04,Soft Drink,6,770,South,CUST0393,Cash,Completed,6,770,2025-08-04
4968,3400,2025-07-21,Tomato Paste,4,710,East,CUST0393,Transfer,Completed,4,710,07-21-2025
2660,3400,2025-07-21,Tomato Paste,4,710,East,CUST0393,Transfer,Completed,4,710,2025-07-21
4368,3471,2025-10-17,Eggs,4,1960,South,CUST0452,Transfer,Pending,4,1960,2025-10-17
4154,3471,2025-10-17,<NA>,<NA>,1960,South,CUST0452,Transfer,Pending,<NA>,1960,2025-10-17
818,3591,2025-02-21,Pepper,4,810,Northh,CUST0501,Transfer,Completed,4,810,2025-02-21
1488,3591,2025-02-21,Pepper,4,810,North,CUST0501,Transfer,Completed,4,810,2025-02-21
1483,3665,2025-05-06,Yam,4,1850,West,CUST0231,Pos,Completed,4,1850,2025-05-06
5066,3665,2025-05-06,Yam,4,1850,West,CUST0231,Pos,<NA>,4,1850,2025-05-06
2735,3925,2025-02-18,Milk,3,1390,North,CUST0278,Cash,<NA>,3,1390,2025-02-18
1848,3925,2025-02-18,Milk,3,1390,North,CUST0278,Cash,Completed,3,1390,2025-02-18
4365,3973,2025-04-06,Water,3,450,West,CUST0637,Pos,<NA>,3,450,2025-04-06
4939,3973,2025-04-06,Water,3,450,West,CUST0637,Pos,Completed,3,450,2025-04-06
2483,4085,2025-10-09,Eggs,4,1930,West,<NA>,Transfer,Completed,4,1930,2025-10-09
208,4085,2025-10-09,Eggs,4,1930,West,CUST0587,Transfer,Completed,4,1930,"Oct 9, 2025"
116,4289,2025-09-20,Rice,5,1670,West,CUST0440,Cash,Completed,Five,1670,2025-09-20
3588,4289,2025-09-20,Rice,7,1670,West,CUST0440,Cash,Completed,7,1670,2025-09-20
2607,4306,2025-08-14,Toothpaste,1,1090,North,CUST0539,Transfer,Completed,1,1090,2025-08-14
3968,4306,2025-08-14,Toothpaste,1,1090,North,UNKNOWN,Transfer,Completed,1,1090,2025-08-14
4619,4418,NaT,Coffee,4,2210,West,CUST0241,Transfer,Completed,4,2210,2025-00-12
3015,4418,2025-02-01,Coffee,4,2210,West,CUST0241,Transfer,Completed,4,2210,2025-02-01
4948,4970,2025-11-29,Groundnut Oil,1,2180,South,CUST0489,Pos,Completed,1,2180,2025-11-29
545,4970,2025-11-29,Groundnut Oil,1,2180,South,CUST0489,Pos,Completed,1,2180,2025-11-29
2866,5062,2025-03-03,Toothpaste,5,1170,West,CUST0343,Cash,Completed,5,1170,2025-03-03
3822,5062,2025-03-03,Toothpaste,5,1170,West,CUST0343,Pos,Completed,5,1170,2025-03-03
1490,5178,2025-06-01,Yam,6,1470,North,CUST0208,Transfer,Completed,6,1470,2025-06-01
852,5178,2025-06-01,<NA>,6,1470,North,CUST0208,Transfer,Completed,6,1470,2025-06-01
3640,5496,2025-09-19,Bread,7,880,North,CUST0609,Transfer,Pending,7,880,2025-09-19
3947,5496,2025-09-19,Bread,<NA>,880,North,CUST0609,Transfer,Pending,<NA>,880,2025-09-19
812,5608,2025-11-23,Carrot,<NA>,760,North,CUST0361,Cash,Completed,<NA>,760,2025-11-23
151,5608,2025-11-23,Carrot,1,2000,North,CUST0361,Cash,Completed,1,2K,2025-11-23
2819,5714,2025-10-11,Milk,6,1250,South,CUST0415,Transfer,Returned,6,1250,2025-10-11
3602,5714,2025-10-11,Milk,<NA>,1250,South,CUST0415,Transfer,Returned,<NA>,1250,2025-10-11
3387,5848,2025-09-30,Water,4,520,East,CUST0363,Cash,Completed,4,520,2025-09-30
3821,5848,2025-09-30,Water,4,520,East,<NA>,Cash,Completed,4,520,2025-09-30

In [28]:
import pandas as pd

# Remove non-alphanumeric characters from customer IDs and keep uppercase.
# Missing IDs remain missing.
df["customer_id"] = (
    df["customer_id"]
    .astype("string")
    .str.replace(r"[^A-Za-z0-9]+", "", regex=True)
    .str.upper()
    .replace("", pd.NA)
)

# Separate rows with and without an order ID so missing IDs aren't all merged.
has_order_id = df["order_id"].notna()
with_id = df.loc[has_order_id].copy()
without_id = df.loc[~has_order_id].copy()

# Prefer the least-missing row for each order ID; stable sorting preserves
# the original row order when rows have the same number of missing values.
with_id["_missing_count"] = with_id.isna().sum(axis=1)
with_id = with_id.sort_values("_missing_count", kind="stable")
with_id = with_id.drop_duplicates(subset="order_id", keep="first")
with_id = with_id.drop(columns="_missing_count")

# Keep rows with missing order IDs, then sort IDs highest to lowest.
df = pd.concat([with_id, without_id], ignore_index=True)
df["_order_id_sort"] = pd.to_numeric(df["order_id"], errors="coerce")
df = (
    df.sort_values("_order_id_sort", ascending=False, na_position="last", kind="stable")
      .drop(columns="_order_id_sort")
      .reset_index(drop=True)
)

In [29]:
df

,order_id,order_date,product,qty,price,region,customer_id,payment_method,status,qty_original,price_original,order_date_original
0,6150,2025-12-23,Carrot,8,900,Northh,CUST0231,Pos,Completed,8,900,2025-12-23
1,6149,2025-01-20,Maggi,9,490,North,CUST0639,Transfer,Completed,9,490,2025-01-20
2,6148,2025-10-28,Toothpaste,2,1270,East,CUST0416,Pos,Completed,2,1270,2025-10-28
3,6147,2025-01-22,Beans,1,1610,North,CUST0566,Transfer,Returned,1,1610,2025-01-22
4,6146,2025-08-12,Cabbage,1,830,East,CUST0283,Transfer,Completed,1,830,2025-08-12
...,...,...,...,...,...,...,...,...,...,...,...,...
5145,Ord-5807,2025-01-30,Beans,11,1440,South,CUST0103,Transfer,Completed,11,1440,2025-01-30
5146,Ord-7441,2025-09-10,<NA>,8,2760,East,CUST0383,Pos,Completed,8,2760,2025-09-10
5147,Ord-1829,2025-03-08,<NA>,2,930,South,CUST0636,Cash,Pending,2,930,2025-03-08
5148,Ord-1609,NaT,Water,5,420,South,CUST0226,Transfer,Completed,5,420,<NA>
5149,Ord-3218,2025-04-11,Soft Drink,<NA>,860,<NA>,CUST0233,Pos,Completed,<NA>,860,2025-04-11

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5150 entries, 0 to 5149
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             5150 non-null   string
 1   order_date           5034 non-null   datetime64[us]
 2   product              5023 non-null   string
 3   qty                  4956 non-null   Int64
 4   price                5011 non-null   Int64
 5   region               5007 non-null   string
 6   customer_id          4986 non-null   string
 7   payment_method       5048 non-null   string
 8   status               5076 non-null   string
 9   qty_original         4969 non-null   string
 10  price_original       5034 non-null   string
 11  order_date_original  5057 non-null   string
dtypes: Int64(2), datetime64[us](1), string(9)
memory usage: 493.0 KB

In [31]:
# Preserve which values were actually missing before estimating anything.
df["qty_was_missing"] = df["qty"].isna()
df["price_was_missing"] = df["price"].isna()

# Fill these categories for grouping/display; this does not invent a customer identity.
for column in ["product", "region"]:
    df[column] = df[column].astype("string").str.strip().fillna("Unknown")

In [32]:
df.head()

,order_id,order_date,product,qty,price,region,customer_id,payment_method,status,qty_original,price_original,order_date_original,qty_was_missing,price_was_missing
0,6150,2025-12-23,Carrot,8,900,Northh,CUST0231,Pos,Completed,8,900,2025-12-23,False,False
1,6149,2025-01-20,Maggi,9,490,North,CUST0639,Transfer,Completed,9,490,2025-01-20,False,False
2,6148,2025-10-28,Toothpaste,2,1270,East,CUST0416,Pos,Completed,2,1270,2025-10-28,False,False
3,6147,2025-01-22,Beans,1,1610,North,CUST0566,Transfer,Returned,1,1610,2025-01-22,False,False
4,6146,2025-08-12,Cabbage,1,830,East,CUST0283,Transfer,Completed,1,830,2025-08-12,False,False

In [33]:
# Fill missing quantity with the average quantity for that product.
df["qty"] = df["qty"].fillna(
    df.groupby("product")["qty"].transform("mean").round().astype("Int64")
)

# Fill missing price with the average price for that product and region.
df["price"] = df["price"].fillna(
    df.groupby(["product", "region"])["price"]
      .transform("mean")
      .round()
      .astype("Int64")
)

In [34]:
df.isna().sum()

order_id                 0
order_date             116
product                  0
qty                      0
price                    0
region                   0
customer_id            164
payment_method         102
status                  74
qty_original           181
price_original         116
order_date_original     93
qty_was_missing          0
price_was_missing        0
dtype: int64

In [38]:
for column in ["customer_id", "payment_method", "status"]:
    df[column] = df[column].astype("string").str.strip().fillna("Unknown")

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5150 entries, 0 to 5149
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             5150 non-null   string
 1   order_date           5034 non-null   datetime64[us]
 2   product              5150 non-null   string
 3   qty                  5150 non-null   Int64
 4   price                5150 non-null   Int64
 5   region               5150 non-null   string
 6   customer_id          5150 non-null   string
 7   payment_method       5150 non-null   string
 8   status               5150 non-null   string
 9   qty_original         4969 non-null   string
 10  price_original       5034 non-null   string
 11  order_date_original  5057 non-null   string
 12  qty_was_missing      5150 non-null   bool
 13  price_was_missing    5150 non-null   bool
dtypes: Int64(2), bool(2), datetime64[us](1), string(9)
memory usage: 503.1 KB

In [43]:
# Remove raw numeric text columns; keep qty_was_missing and price_was_missing.
df = df.drop(columns=["price_original", "qty_original"], errors="ignore")

# Keep the full dataset and its parsed order_date column as the cleaned snapshot.
# Keep order_date_original if you want to retain the source date text for auditing.
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")

# Use only dated rows for time-based analysis.
dated_sales = df.loc[df["order_date"].notna()].copy()

print("Rows in full cleaned dataset:", len(df))
print("Rows available for date-based analysis:", len(dated_sales))
print("Rows with missing dates:", df["order_date"].isna().sum())

Rows in full cleaned dataset: 5150
Rows available for date-based analysis: 5034
Rows with missing dates: 116

In [44]:
df

,order_id,order_date,product,qty,price,region,customer_id,payment_method,status,order_date_original,qty_was_missing,price_was_missing
0,6150,2025-12-23,Carrot,8,900,Northh,CUST0231,Pos,Completed,2025-12-23,False,False
1,6149,2025-01-20,Maggi,9,490,North,CUST0639,Transfer,Completed,2025-01-20,False,False
2,6148,2025-10-28,Toothpaste,2,1270,East,CUST0416,Pos,Completed,2025-10-28,False,False
3,6147,2025-01-22,Beans,1,1610,North,CUST0566,Transfer,Returned,2025-01-22,False,False
4,6146,2025-08-12,Cabbage,1,830,East,CUST0283,Transfer,Completed,2025-08-12,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
5145,Ord-5807,2025-01-30,Beans,11,1440,South,CUST0103,Transfer,Completed,2025-01-30,False,False
5146,Ord-7441,2025-09-10,Unknown,8,2760,East,CUST0383,Pos,Completed,2025-09-10,False,False
5147,Ord-1829,2025-03-08,Unknown,2,930,South,CUST0636,Cash,Pending,2025-03-08,False,False
5148,Ord-1609,NaT,Water,5,420,South,CUST0226,Transfer,Completed,<NA>,False,False
5149,Ord-3218,2025-04-11,Soft Drink,5,860,Unknown,CUST0233,Pos,Completed,2025-04-11,True,False

In [49]:
df.region.unique()

<StringArray>
['North', 'East', 'West', 'South', 'Unknown']
Length: 5, dtype: str

In [48]:
# Normalize region labels, including spacing/case variations.
region = df["region"].astype("string").str.strip()
df["region"] = region.map({
    "Northh": "North",
    "Noth": "North",
    "Eastern": "East",
    "Sout": "South",
}).fillna(region.str.title())

In [50]:
from pathlib import Path
import pandas as pd

# Create the output folder if it does not already exist.
data_folder = Path("data")
data_folder.mkdir(parents=True, exist_ok=True)

# Save the complete cleaned dataset, including rows with missing dates.
df.to_csv(data_folder / "cleaned_data.csv", index=False)

# Save a separate copy for analyses that require a valid order date.
date_analysis = df.loc[df["order_date"].notna()].copy()
date_analysis.to_csv(data_folder / "date_analysis.csv", index=False)

print(f"Saved full cleaned data: {data_folder / 'cleaned_data.csv'}")
print(f"Saved date-analysis data: {data_folder / 'date_analysis.csv'}")

Saved full cleaned data: data\cleaned_data.csv
Saved date-analysis data: data\date_analysis.csv

## Phase 2 — Data Cleaning and Preparation

We standardized text and category labels, cleaned customer IDs, and converted quantity, price, and order date to appropriate data types. Missing quantities and prices were filled using group averages, while flags were retained to identify originally missing values. Duplicate order IDs were handled by keeping the most complete row. Rows with missing dates were preserved in the full dataset and excluded only from date-based analysis.

## Phase 3 — Exploratory Data Analysis

We will use the cleaned dataset to investigate sales performance and identify patterns supported by the data. We will compare results across products, regions, payment methods, and time where dates are available. We will distinguish recorded values from estimates and explain what each result shows before drawing business conclusions.

Provided concise Markdown cells summarizing Phase 2 cleaning and introducing Phase 3 exploratory analysis, with no code snippets.